# Generated by IBM TransformationAdvisor
# Tue Aug 11 02:57:58 UTC 2020

import sys
import os

global  AdminConfig

def getNodeId (prompt):
    nodeList = AdminConfig.list("Node").split("\n")

    if (len(nodeList) == 1):
        node = nodeList[0]
    else:
        print ""
        print "Available Nodes:"

        nodeNameList = []

        for item in nodeList:
            item = item.rstrip()
            name = getName(item) 

            nodeNameList.append(name)
            print "   " + name

        DefaultNode = nodeNameList[0]
        if (prompt == ""):
            prompt = "Select the desired node"

        nodeName = getValidInput(prompt+" ["+DefaultNode+"]:", DefaultNode, nodeNameList )

        index = nodeNameList.index(nodeName)
        node = nodeList[index]

    return node


def getServerId (prompt):
    serverList = AdminConfig.list("Server").split("\n")

    if (len(serverList) == 1):
        server = serverList[0]
    else:
        print ""
        print "Available Servers:"

        serverNameList = []

        for item in serverList:
            item = item.rstrip()
            name = getName(item)

            serverNameList.append(name)
            print "   " + name

        DefaultServer = serverNameList[0]
        if (prompt == ""):
            prompt = "Select the desired server"
        serverName = getValidInput(prompt+" ["+DefaultServer+"]:", DefaultServer, serverNameList )

        index = serverNameList.index(serverName)
        server = serverList[index]

    return server


def getName (objectId):
    endIndex = (objectId.find("(c") - 1)
    stIndex = 0
    if (objectId.find("\"") == 0):
        stIndex = 1
    return objectId[stIndex:endIndex+1]


print "Installing application ..."

node = getName(getNodeId(""))
server = getName(getServerId(""))

parms = "-appname thinkdemoappwar"
parms += " -node " + node + " -server " + server
parms += " -nouseMetaDataFromBinary"
parms += " -MapWebModToVH [[.* .* default_host]]"
#parms += ' -MapResRefToEJB [[ "Think Web Application" "" thinkdemoapp-0.0.1-snapshot.war,WEB-INF/web.xml db2con javax.sql.DataSource db2con "" "" ]]'
#parms += ' -MapResRefToEJB [[ThinkDemoApp .* thinkdemoapp-0.0.1-snapshot.war,WEB-INF/web.xml db2con javax.sql.DataSource]]'
parms += ' -MapResRefToEJB [[ "Thinkdemoapp","",'thinkdemoapp-0.0.1-snapshot.war,WEB-INF/web.xml','jdbc/pakdemo','javax.sql.DataSource','jbdc/db2con','DefaultPrincipalMapping','was01Node01/db2user',""]]'

print "parms:"
print parms

app = AdminApp.install("/work/config/thinkdemoapp-0.0.1-snapshot.war", [parms])

print "app:"
print app

AdminConfig.save()

